name: "Docker container action"
description: "Say hello"
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
    time:
      description: "Current time"
runs:
  using: 'docker'
  image: Dockerfile
  args:
  -  '${{ inputs.who-to-greet }}'
