name: GitHub Actions Demo

on: 
  push:
    branches:
    - main
    paths-ignore:
    - '.github/**'
  pull_request:
    branches:
    - main
  schedule:
  - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      enviornment:
        description: "Name of the enviornment"
        type: environment
        required: true
        
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job triggered event: ${{  github.event_name }}"
          echo "The name of the branch: ${{ github.ref }}"
      - uses: actions/checkout@v4
      - name: List files
        run: |
          echo "Listing files... from repo ${{ github.repository }}"
          ls -la

  Test:
    runs-on: ubuntu-latest
    needs: ["Build"]
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - name: Deploy to  Test
        run: |
          echo "Loading ...  Test"
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    needs: ["Build"]
    steps:
      - name: Deploy to Load-Test
        run: |
          echo "Loading ...  Load-Test"
  Production:
    if: github.event.inputs.environment == 'Production'
    runs-on: ubuntu-latest
    environment: Production
    needs: ["Load-Test","Test"]
    steps:
      - name: Deploy to Production
        run: |
          echo "Loading ... Production"
          
