name: "Run docker container action"
on: 
  push:
    branches: [main]
    paths: ["hello-world-docker-action/**"]
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: ./hello-world-docker-action
       id: docker-step
       with:
         who-to-greet: "Diogo"
     - name: "Current time step"
       run: "${{ steps.docker-step.outputs.time}}"
      
      
    
